language: php
php:
  - 5.6

env:
  - DB=mysql

before_script:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - "mysql -u root -e 'create database caketoodoo_test;'"
  - "mysql -u root -e \"grant all on caketoodoo_test.* to 'caketoodoo';\""

sudo: required
script:
  - phpunit

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true

notifications:
  email: false
