language: php
php:
  - 5.6

env:
  - DB=mysql

before_script:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - "mysql -u root -e 'create database caketoodoo_test;'"
  - "mysql -u root -e \"grant all on caketoodoo_test.* to 'caketoodoo';\""
  - chmod -R 777 ../cakephp/app/tmp

sudo: required
script:
  - ./lib/Cake/Console/cake test app

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true

notifications:
  email: false
